In [2]:
import pandas as pd

cafe = pd.DataFrame({
    '메뉴':   ['아메리카노', '카페라떼', '녹차라떼', '자몽에이드', '레몬에이드'],
    '가격':   [4000, 4500, 5000, 5500, 5000],
    '분류':   ['커피', '커피', '논커피', '음료', '음료'],
    '재고':   [30, 12, 8, 20, 15]
})
cafe

      메뉴    가격   분류  재고
0  아메리카노  4000   커피  30
1   카페라떼  4500   커피  12
2   녹차라떼  5000  논커피   8
3  자몽에이드  5500   음료  20
4  레몬에이드  5000   음료  15

In [24]:
## 문제 1. Series vs DataFrame
#(1) Series로 뽑기
cafe['메뉴']
#(2) DataFrame(표 모양 유지)으로 뽑기
cafe[['메뉴','가격']]
#(3) type()으로 두 결과의 타입이 다름을 확인
type(cafe['메뉴'])
type(cafe[['메뉴','가격']])

      메뉴    가격
0  아메리카노  4000
1   카페라떼  4500
2   녹차라떼  5000
3  자몽에이드  5500
4  레몬에이드  5000

In [42]:
## 문제 2. loc vs iloc
#(1) loc을 사용해 인덱스 1~3 행의 메뉴, 가격 열을 출력하라.
cafe.loc[1, ['메뉴','가격']]
cafe.loc[2, ['메뉴','가격']]
cafe.loc[3, ['메뉴','가격']]
#(2) iloc을 사용해 앞 3행, 앞 2열을 출력하라.
#(3) 두 결과에서 몇 개의 행이 나왔는지 비교하고, 왜 다른지 한 줄로 설명하라.

메뉴    자몽에이드
가격     5500
Name: 3, dtype: object

In [55]:
##문제 3. 열 추가 + 조건부 값 수정
#(1) 가격의 10%를 부가세로 계산한 부가세 열을 추가하라. (정수형으로)
cafe['부가세'] = (cafe['가격'] * 10/100).astype(int)
cafe
#(2) 가격과 부가세를 더한 최종가 열을 추가하라.
cafe['최종가'] = (cafe['가격'] + cafe['부가세']).astype(int)
cafe
#(3) 분류가 '음료'인 행만 재고를 50으로 바꿔라.
cafe.loc[cafe['분류']=='음료', '재고'] = 50
cafe

      메뉴    가격   분류  재고  부가세   최종가
0  아메리카노  4000   커피  30  400  4400
1   카페라떼  4500   커피  12  450  4950
2   녹차라떼  5000  논커피   8  500  5500
3  자몽에이드  5500   음료  50  550  6050
4  레몬에이드  5000   음료  50  500  5500

In [61]:
##문제 4. 조건 필터 + 정렬
#분류가 '커피'가 아니면서 가격이 5000 이상인 행만 골라라.
cafe[(cafe['분류'] != '커피')&(cafe['가격']>=5000)]
#그 결과를 가격 내림차순으로 정렬하라.

#정렬된 결과에서 메뉴, 가격 열만 남겨라.

      메뉴    가격   분류  재고  부가세   최종가
2   녹차라떼  5000  논커피   8  500  5500
3  자몽에이드  5500   음료  50  550  6050
4  레몬에이드  5000   음료  50  500  5500